### ISSUE TITLE
language options for posts

### ISSUE THREAD

**Issue by ToriRae324** [atkinsta/Project2#2]
what lang options should we have?

[ ] html 
[ ] css 
[ ] javascript 
[ ] node?
[ ] more?

**Comment by ToriRae324** [comment]
do we need to have a sep table/model for languages so the post can have a drop drown?

**Comment by lhernandez5** [comment]
As of now the index page has these lang options:
1. JavaScript 
2. Java
3. C
4. C#

**Comment by ToriRae324** [comment]
What about CSS?

**Comment by lhernandez5** [comment]
I can add it
